#!/bin/bash
cd /var/TicTacToe
git pull > /dev/null || rm -rf *; git clone https://github.com/threeheadedmonkeyteam/three_ticktactoe
gradle build > /dev/null
cp /var/TicTacToe/html/files/* /var/www/html/files/ > /dev/null
