language: java
sudo: false # faster builds
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./versioncheck
  - ./gradlew check
after_success:
  - bash <(curl -s https://codecov.io/bash)
