/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andri' at '25/10/16 11:39' with Gradle 3.1
 *
 * @author andri, @date 25/10/16 11:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
