/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andri' at '25/10/16 11:39' with Gradle 3.1
 *
 * @author thmt, @date 25/10/16 11:39
 */
import static java.lang.System.*;

public class TicTacToe {
    public static void main(String [ ] args) {
        Console intrfc = new Console();
	Game game = new Game();
    }
	
    public TicTacToe() {
    }

    public boolean testMethod() {
        return true;
    }
}
