import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'thmt' at '25/10/16 11:39' with Gradle 3.1
 *
 * @author thmt, @date 25/10/16 11:39
 */
public class TicTacToeTest {
    @Test public void shouldReturnTrue() {
        TicTacToe game = new TicTacToe();       
        assertEquals(true, game.testMethod());
    }
}
